// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('fromNow', []);

  angular.module('fromNow').directive('fromNow', function(moment) {
    return {
      restrict: 'A',
      link: function(_, element, attrs) {
        return element.text(moment(attrs.datetime).fromNow());
      }
    };
  });

  angular.module('fromNow').factory('moment', function($window) {
    return $window.moment;
  });

}).call(this);
